x-minio-common: &minio-common
  image: minio/minio:latest
  command: server --console-address ":9001" http://minio1/data http://minio2/data
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  restart: unless-stopped

services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: unless-stopped
  
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - minio_data1:/data

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - minio_data2:/data

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000" # FastAPI
      - "9000:9000" # MinIO S3 API
      - "9001:9001" # MinIO Console
    depends_on:
      - minio1
      - minio2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data1:
  minio_data2: