FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1
# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app


ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

# Copy dependency files and app
COPY pyproject.toml uv.lock ./.python-version ./

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project --no-dev

# Copy the project into the image
COPY app ./app
COPY alembic ./alembic
COPY alembic.ini ./alembic.ini

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev

# CMD ["uv", "run", "fastapi", "dev", "app/main.py", "--host", "0.0.0.0"]
COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]