"""add_namespaces

Revision ID: 432505e7b4c1
Revises: e9fcc6642e0e
Create Date: 2026-07-24 15:54:20.564015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432505e7b4c1'
down_revision: Union[str, Sequence[str], None] = 'e9fcc6642e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namespaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=True),
    sa.Column('storage_quota_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    # Insert default Clerk namespace
    op.execute(
        "INSERT INTO namespaces (id, name, created_at, updated_at) "
        "VALUES ('00000000-0000-0000-0000-000000000001', 'clerk', now(), now())"
    )

    op.add_column('files', sa.Column('namespace_id', sa.Uuid(), server_default='00000000-0000-0000-0000-000000000001', nullable=False))
    op.alter_column('files', 'namespace_id', server_default=None)
    op.create_foreign_key(None, 'files', 'namespaces', ['namespace_id'], ['id'], ondelete='RESTRICT')
    
    op.add_column('folders', sa.Column('namespace_id', sa.Uuid(), server_default='00000000-0000-0000-0000-000000000001', nullable=False))
    op.alter_column('folders', 'namespace_id', server_default=None)
    op.create_foreign_key(None, 'folders', 'namespaces', ['namespace_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_column('folders', 'namespace_id')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'namespace_id')
    op.drop_table('namespaces')
    # ### end Alembic commands ###
