"""namespace_quota_fields

Revision ID: 61ff961581fa
Revises: 7bb7e4d614c9
Create Date: 2026-08-02 18:41:27.630244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ff961581fa'
down_revision: Union[str, Sequence[str], None] = '7bb7e4d614c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('namespaces', 'storage_quota_bytes', new_column_name='quota_bytes')
    op.add_column('namespaces', sa.Column('used_bytes', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('namespaces', sa.Column('files_count', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('namespaces', 'quota_bytes', new_column_name='storage_quota_bytes')
    op.drop_column('namespaces', 'files_count')
    op.drop_column('namespaces', 'used_bytes')
    # ### end Alembic commands ###
