"""make quota nullable

Revision ID: 7bb7e4d614c9
Revises: ae048947329f
Create Date: 2026-07-31 22:04:08.777705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb7e4d614c9'
down_revision: Union[str, Sequence[str], None] = 'ae048947329f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('b2b_user_quotas', 'allocated_quota_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('b2b_user_quotas', 'allocated_quota_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
