"""extract api keys

Revision ID: 9057e6d01fa2
Revises: fc465064bb12
Create Date: 2026-07-31 17:03:11.792338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9057e6d01fa2'
down_revision: Union[str, Sequence[str], None] = 'fc465064bb12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namespace_api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('namespace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.drop_column('namespaces', 'api_key_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namespaces', sa.Column('api_key_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('namespace_api_keys')
    # ### end Alembic commands ###
