"""initial migration

Revision ID: ac9785013892
Revises: 
Create Date: 2026-07-07 15:28:17.008052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = 'ac9785013892'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('path', app.models.base.LtreeType(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('set_access_level', sa.Integer(), nullable=False),
    sa.Column('actual_access_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physical_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('internal_key', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_files_file_hash'), 'physical_files', ['file_hash'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('path', app.models.base.LtreeType(), nullable=True),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('set_access_level', sa.Integer(), nullable=False),
    sa.Column('actual_access_level', sa.Integer(), nullable=False),
    sa.Column('physical_file_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['physical_file_id'], ['physical_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder_allowed_users',
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id', 'user_id')
    )
    op.create_table('file_allowed_users',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', 'user_id')
    )
    op.create_table('share_links',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share_links')
    op.drop_table('file_allowed_users')
    op.drop_table('folder_allowed_users')
    op.drop_table('files')
    op.drop_index(op.f('ix_physical_files_file_hash'), table_name='physical_files')
    op.drop_table('physical_files')
    op.drop_table('folders')
    # ### end Alembic commands ###
