"""add_namespace_author_id

Revision ID: fc465064bb12
Revises: 432505e7b4c1
Create Date: 2026-07-27 13:17:34.720033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc465064bb12'
down_revision: Union[str, Sequence[str], None] = '432505e7b4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namespaces', sa.Column('author_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('namespaces', 'author_id')
    # ### end Alembic commands ###
